### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by theolivenbaum** [curiosity-ai/tesserae#1]
- [x] Button: https://developer.microsoft.com/en-us/fabric#/controls/web/button

- [x] Checkbox: https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox
- [x] Toggle: https://developer.microsoft.com/en-us/fabric#/controls/web/toggle
- [x] Slider: https://developer.microsoft.com/en-us/fabric#/controls/web/slider
- [x] TextField: https://developer.microsoft.com/en-us/fabric#/controls/web/textfield (no need for masks. nice to have the validation stuff with error messages)
- [x] ChoiceGroup: https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup

- [x] Layers: https://developer.microsoft.com/en-us/fabric#/controls/web/layer (they use layers to render content on top of others, good idea to create a similar approach to use for ex. on context menus, and all modal-like surfaces like Modal, Panel, Dialog, Callout, etc)

- [x] Stack: https://developer.microsoft.com/en-us/fabric#/controls/web/stack (make sure to use similar approach using flexbox as fabric css, the examples with resizing are super useful to test behaviour)
- [x] Pivot: https://developer.microsoft.com/en-us/fabric#/controls/web/pivot (can copy from TabbedView)
- [x] Nav: https://developer.microsoft.com/en-us/fabric#/controls/web/nav
- [ ] Combobox: https://developer.microsoft.com/en-us/fabric#/controls/web/combobox
- [x] Dropdown:https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown
- [ ] List: https://developer.microsoft.com/en-us/fabric#/controls/web/list
- [ ] DetailsList: https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist
- [ ] CommandBar: https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar
- [x] ContextualMenu: https://developer.microsoft.com/en-us/fabric#/controls/web/contextualmenu (can copy from Menu)
- [x] Breadcrumb: https://developer.microsoft.com/en-us/fabric#/controls/web/breadcrumb
- [ ] OverflowSet: https://developer.microsoft.com/en-us/fabric#/controls/web/overflowset
- [ ] GroupedList: https://developer.microsoft.com/en-us/fabric#/controls/web/groupedlist
- [ ] Picker: https://developer.microsoft.com/en-us/fabric#/controls/web/pickers
- [ ] SpinButton: https://developer.microsoft.com/en-us/fabric#/controls/web/spinbutton

- [x] Modal: https://developer.microsoft.com/en-us/fabric#/controls/web/modal
- [x] Panel: https://developer.microsoft.com/en-us/fabric#/controls/web/panel
- [x] Dialog: https://developer.microsoft.com/en-us/fabric#/controls/web/dialog
- [ ] Callout: https://developer.microsoft.com/en-us/fabric#/controls/web/callout
- [ ] Tooltip: https://developer.microsoft.com/en-us/fabric#/controls/web/tooltip (the fabric approach of using a Tooltip Host to wrap the inner content is quite elegant - check the example code there)
